# Generated by Django 3.1.3 on 2022-08-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientSite', '0002_voluntieer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
