# Generated by Django 3.1.3 on 2022-08-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientSite', '0003_contactusmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsAndEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('news', 'News'), ('event', 'Event')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='newsEvent/')),
            ],
        ),
    ]
