# Generated by Django 3.1.3 on 2022-08-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientSite', '0005_newseventimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('partner', 'Partner'), ('donor', 'Donor')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
            ],
        ),
    ]
