# Generated by Django 3.1.3 on 2022-08-20 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientSite', '0006_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientSite.project')),
            ],
        ),
    ]
