# Generated by Django 3.1.3 on 2022-08-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientSite', '0007_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandevents',
            name='type',
            field=models.CharField(choices=[('event', 'Event'), ('news', 'News')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('donor', 'Donor'), ('partner', 'Partner')], max_length=20),
        ),
    ]
