# Generated by Django 3.1.3 on 2022-08-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientSite', '0008_auto_20220820_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallary/')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('partner', 'Partner'), ('donor', 'Donor')], max_length=20),
        ),
    ]
