# Generated by Django 3.1.3 on 2022-08-20 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientSite', '0009_auto_20220820_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientSite.imagegallary')),
            ],
        ),
    ]
