# Generated by Django 3.1.3 on 2022-08-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientSite', '0011_auto_20220820_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntieer',
            name='social_links',
        ),
        migrations.AddField(
            model_name='voluntieer',
            name='facebook',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='voluntieer',
            name='linkedin',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
