# Generated by Django 3.1.3 on 2022-08-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientSite', '0012_auto_20220821_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='donor_partner',
            field=models.CharField(default='default', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsandevents',
            name='type',
            field=models.CharField(choices=[('news', 'News'), ('event', 'Event')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('partner', 'Partner'), ('donor', 'Donor')], max_length=20),
        ),
    ]
